/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_smgui_common_JNITest */

#ifndef _Included_net_smgui_common_JNITest
#define _Included_net_smgui_common_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_smgui_common_JNITest
 * Method:    Hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_smgui_common_JNITest_Hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
